name: Build App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'self-hosted'

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
